name: CI-24-Hour

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Reference the major version of a release
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # This is important to avoid using the default token

      - name: Set up git user
        run: |
          git config user.name ${{ secrets.GIT_USER }}
          git config user.email ${{ secrets.GIT_EMAIL }}

      - name: Authenticate with GitHub token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

      - name: Run a one-line script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo " print('hello world') " >> important_file.txt
          git add important_file.txt
          git commit -m "Always green!"
          git push

      - name: Random Exit 1
        id: random_check
        run: |
          RANDOM_NUMBER=$((1 + RANDOM % 3))
          echo "Generated number: $RANDOM_NUMBER"
          if [ $RANDOM_NUMBER -ne 3 ]; then
            echo "Random number is not 3. Exiting."
            exit 0
          fi
          
      - name: Run a one-line script 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo " print('hello world') " >> important_file.txt
          git add important_file.txt
          git commit -m "Always green!"
          git push

      - name: Random Exit 2
        id: random_check_2
        run: |
          RANDOM_NUMBER=$((1 + RANDOM % 3))
          echo "Generated number: $RANDOM_NUMBER"
          if [ $RANDOM_NUMBER -ne 3 ]; then
            echo "Random number is not 3. Exiting."
            exit 0
          fi

      - name: Run a one-line script 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo " print('hello world') " >> important_file.txt
          git add important_file.txt
          git commit -m "Always green!"
          git push

      - name: Random Exit 3
        id: random_check_3
        run: |
          RANDOM_NUMBER=$((1 + RANDOM % 3))
          echo "Generated number: $RANDOM_NUMBER"
          if [ $RANDOM_NUMBER -ne 3 ]; then
            echo "Random number is not 3. Exiting."
            exit 0
          fi

      - name: Run a one-line script 4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo " print('hello world') " >> important_file.txt
          git add important_file.txt
          git commit -m "Always green!"
          git push

      - name: Random Exit 4
        id: random_check_4
        run: |
          RANDOM_NUMBER=$((1 + RANDOM % 3))
          echo "Generated number: $RANDOM_NUMBER"
          if [ $RANDOM_NUMBER -ne 3 ]; then
            echo "Random number is not 3. Exiting."
            exit 0
          fi

      - name: Run a one-line script 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo " print('hello world') " >> important_file.txt
          git add important_file.txt
          git commit -m "Always green!"
          git push

      - name: Random Exit 5
        id: random_check_5
        run: |
          RANDOM_NUMBER=$((1 + RANDOM % 3))
          echo "Generated number: $RANDOM_NUMBER"
          if [ $RANDOM_NUMBER -ne 3 ]; then
            echo "Random number is not 3. Exiting."
            exit 0
          fi
