name: CI-24-Hour-5

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate random number and check if it's 5
        id: random_check
        run: |
          RANDOM_NUMBER=$((1 + RANDOM % 5))
          echo "Generated number: $RANDOM_NUMBER"
          if [ $RANDOM_NUMBER -ne 5 ]; then
            echo "Random number is not 5. Exiting."
            exit 0
          fi

      # Reference the major version of a release
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # This is important to avoid using the default token

      - name: Set up git user
        run: |
          git config user.name ${{ secrets.GIT_USER }}
          git config user.email ${{ secrets.GIT_EMAIL }}

      - name: Authenticate with GitHub token
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git

      - name: Run a one-line script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo " print('hello world') " >> important_file.txt
          git add important_file.txt
          git commit -m "Always green!"
          git push
