name: CI-5-Hour

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  create_commit_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        uses: actions/setup-gh-cli@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a new file
        run: echo "This is a new file created by GitHub Actions" > newfile.txt

      - name: Commit the new file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add newfile.txt
          git commit -m "Add newfile.txt created by GitHub Actions"
          git push

