name: CI-5-Hour

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      # Reference the major version of a release
      - uses: actions/checkout@v4
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create important file
        run: date +%s > important.txt      
      - name: Commit report
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git config --global user.name 'thomaslillo'
          git config --global user.email 'thomas.j.lillo@gmail.com'
          git add .
          git commit -am "Automated report"
          git push

