name: CI-5-Hour

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Reference the major version of a release
    - uses: actions/checkout@v4

    - name: Set up git user
      run: |
        git config user.name ${{ secrets.GIT_USER }}
        git config user.email ${{ secrets.GIT_EMAIL }}

    - name: Run a one-line script
      run: |
        echo " " >> README.md
        git add README.md
        git commit -m "Always green!"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
