name: CI-5-Hour

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Reference the major version of a release
      - uses: actions/checkout@v4
      - name: Create important file
        run: date +%s > important.txt
      - name: Commit report
        run: |
          git config --global user.name 'thomaslillo'
          git config --global user.email 'thomas.j.lillo@gmail.com'
          git add .
          git commit -am "Automated report"
          git push
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
